services:
  php74:
    build:
      context: .
      args:
        PHP_VERSION: "7.4"
    working_dir: /workspace
    volumes:
      - ./:/workspace
    command: ["bash", "-lc", "while true; do sleep 1000; done"]
    tty: true
    stdin_open: true

  php81:
    build:
      context: .
      args:
        PHP_VERSION: "8.1"
    working_dir: /workspace
    volumes:
      - ./:/workspace
    command: ["bash", "-lc", "while true; do sleep 1000; done"]
    tty: true
    stdin_open: true
